powerdata <- read.csv("household_power_consumption.txt",header = TRUE, sep=";")
subpowerdata <- powerdata[powerdata$Date=="2/2/2007" | powerdata$Date=="1/2/2007",]
dt <- strptime(paste(subpowerdata$Date, subpowerdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
par(mar=c(4,4,2,2))
pwr <- (as.numeric(as.character(subpowerdata$Global_active_power)))
plot(dt, pwr, type="l",ylab="Global Active Power",xlab="")
plot(dt, (as.numeric(as.character(subpowerdata$Voltage))), type="l",ylab="Voltage",xlab="datetime")
plot(dt, subpowerdata$Sub_metering_1,type="n",ylab="Energy sub metering",xlab="")
lines(dt, subpowerdata$Sub_metering_1)
lines(dt, subpowerdata$Sub_metering_2, col="red")
lines(dt, subpowerdata$Sub_metering_3, col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),
       col=c("black","red","blue"), lty=1, lwd=2)
pwr2 <- (as.numeric(as.character(subpowerdata$Global_reactive_power)))
plot(dt, pwr2 ,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()